### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by brunolemos** [agrcrobles/react-navigation-web#5]
I'm trying to use this package, but haven't had success yet.

`routes` is undefined or null on [this line](https://github.com/agrcrobles/react-navigation-web/blob/master/src/TabNavigator/index.js#L44):

```js
{Object.keys(routes).map((route, index) =>
```

Maybe it's because you are using `react-navigation@^1.0.0-beta.3` and I'm using `react-navigation@^1.0.0-beta.5`? Could you upgrade it and maybe put it as a `peerDependency`?

**Comment by agrcrobles** [comment]
`react-navigation` version shouldn't be longer an issue.
`routes` shouldn't be undefined if they are declared.
You should pass them to Navigator this [way](https://github.com/agrcrobles/react-navigation-web/blob/master/examples/navigation.js#L8) and declare it like [this](https://github.com/agrcrobles/react-navigation-web/blob/master/examples/tab.js#L57).
